name: Greeting Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a greeting
        - uses: actions/checkout@v4
        - name: Run Python Tests
          run: python3 test_calc.py